browsers:
  - name: chrome
    version:
      - 49 # last supported on XP (keep it so long as it's easy to support)
      - -1..latest
  - name: firefox
    version:
      - 52 # extended support release
      - -1..latest
  - name: safari
    version: -1..latest
  - name: ie
    version: 9..latest
sauce_connect: true
loopback: airtap.local
